POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username" : "RPP",
  "password" : "rahasia",
  "name" : "Rizki Panca"
}

###

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username" : "RPP",
  "password" : "rahasia"
}

###

GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: f278d9db-ca1d-413c-a68a-71966a8be470

###

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 21e2f29c-813d-4f15-975e-29c9f7d63e50

{
  "name" : "Rizki Panca Pamungkas"
}

###

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: 21e2f29c-813d-4f15-975e-29c9f7d63e50

###

POST http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: f278d9db-ca1d-413c-a68a-71966a8be470

{
  "first_name" : "Jumanta",
  "last_name" : "Simatupang",
  "email" : "jumanta@jso.com",
  "phone" : "324234234234"
}

###

GET http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 56cdb760-8206-4b45-b395-0f6ccee60b1b

###

GET http://localhost:3000/api/contacts/1
Content-Type: application/json
Accept: application/json
Authorization: 56cdb760-8206-4b45-b395-0f6ccee60b1b

### Update

PUT http://localhost:3000/api/contacts/1
Content-Type: application/json
Accept: application/json
Authorization: 56cdb760-8206-4b45-b395-0f6ccee60b1b

{
  "first_name": "Jumanta JR",
  "last_name": "Siregar",
  "email": "jumanta@jso.com",
  "phone": "324234234234"
}

### Delete Contact

DELETE http://localhost:3000/api/contacts/317
Content-Type: application/json
Accept: application/json
Authorization: 19dfc22d-4545-45a9-9b36-ec0fc3fee291

### Create Address

POST http://localhost:3000/api/contacts/1/addresses
Content-Type: application/json
Accept: application/json
Authorization: 56cdb760-8206-4b45-b395-0f6ccee60b1b

{
  "street" : "Buah",
  "city" : "Ciawi",
  "province" : "Bogor",
  "country" : "Indonesia",
  "postal_code" : "324234"
}


### List Addresses

GET http://localhost:3000/api/contacts/1/addresses
Content-Type: application/json
Accept: application/json
Authorization: 56cdb760-8206-4b45-b395-0f6ccee60b1b


### Get Address

GET http://localhost:3000/api/contacts/316/addresses/46
Content-Type: application/json
Accept: application/json
Authorization: 19dfc22d-4545-45a9-9b36-ec0fc3fee291

### Update Address

PUT http://localhost:3000/api/contacts/316/addresses/46
Content-Type: application/json
Accept: application/json
Authorization: 19dfc22d-4545-45a9-9b36-ec0fc3fee291

{
  "street" : "Buah Rambutan",
  "city" : "Cigombong",
  "province" : "Jawa Barat",
  "country" : "Indonesia",
  "postal_code" : "324234"
}

### Remove Address

DELETE http://localhost:3000/api/contacts/316/addresses/46
Content-Type: application/json
Accept: application/json
Authorization: 19dfc22d-4545-45a9-9b36-ec0fc3fee291